# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to hardware-overrides.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usbhid"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];


  fileSystems."/" =
    { device = "/dev/mapper/luks-e84e88d5-9d43-4515-abbc-4b74a00e63ee";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-e84e88d5-9d43-4515-abbc-4b74a00e63ee".device = "/dev/disk/by-uuid/e84e88d5-9d43-4515-abbc-4b74a00e63ee";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/065D-05C1";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-02e42960-4936-4e3f-8af3-77e80135dd9f"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
