# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-363d2cca-e5b6-4d0d-9558-e8f58eaa2d34";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-363d2cca-e5b6-4d0d-9558-e8f58eaa2d34".device =
    "/dev/disk/by-uuid/363d2cca-e5b6-4d0d-9558-e8f58eaa2d34";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0B48-8BA6";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  # Priority 1 ensures zram (default priority 5) is preferred
  swapDevices = [
    {
      device = "/dev/mapper/luks-cd21de89-443f-44ff-afb5-18fd412dc80c";
      priority = 1;
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
